from __future__ import annotations

import harn_tui as tui_module


def test_root_package_exports_match_ts_surface() -> None:
    assert tui_module.__all__ == [
        "AutocompleteItem",
        "AutocompleteProvider",
        "AutocompleteSuggestions",
        "CombinedAutocompleteProvider",
        "SlashCommand",
        "Box",
        "CancellableLoader",
        "Editor",
        "EditorOptions",
        "EditorTheme",
        "Image",
        "ImageOptions",
        "ImageTheme",
        "Input",
        "Loader",
        "LoaderIndicatorOptions",
        "DefaultTextStyle",
        "Markdown",
        "MarkdownTheme",
        "SelectItem",
        "SelectList",
        "SelectListLayoutOptions",
        "SelectListTheme",
        "SelectListTruncatePrimaryContext",
        "SettingItem",
        "SettingsList",
        "SettingsListTheme",
        "Spacer",
        "Text",
        "TruncatedText",
        "EditorComponent",
        "FuzzyMatch",
        "fuzzyFilter",
        "fuzzyMatch",
        "getKeybindings",
        "Keybinding",
        "KeybindingConflict",
        "KeybindingDefinition",
        "KeybindingDefinitions",
        "Keybindings",
        "KeybindingsConfig",
        "KeybindingsManager",
        "setKeybindings",
        "TUI_KEYBINDINGS",
        "decodeKittyPrintable",
        "isKeyRelease",
        "isKeyRepeat",
        "isKittyProtocolActive",
        "Key",
        "KeyEventType",
        "KeyId",
        "matchesKey",
        "parseKey",
        "setKittyProtocolActive",
        "StdinBuffer",
        "StdinBufferEventMap",
        "StdinBufferOptions",
        "ProcessTerminal",
        "Terminal",
        "allocateImageId",
        "CellDimensions",
        "calculateImageRows",
        "deleteAllKittyImages",
        "deleteKittyImage",
        "detectCapabilities",
        "encodeITerm2",
        "encodeKitty",
        "getCapabilities",
        "getCellDimensions",
        "getGifDimensions",
        "getImageDimensions",
        "getJpegDimensions",
        "getPngDimensions",
        "getWebpDimensions",
        "hyperlink",
        "ImageDimensions",
        "ImageProtocol",
        "ImageRenderOptions",
        "imageFallback",
        "renderImage",
        "resetCapabilitiesCache",
        "setCapabilities",
        "setCellDimensions",
        "TerminalCapabilities",
        "Component",
        "Container",
        "CURSOR_MARKER",
        "Focusable",
        "isFocusable",
        "OverlayAnchor",
        "OverlayHandle",
        "OverlayMargin",
        "OverlayOptions",
        "SizeValue",
        "TUI",
        "truncateToWidth",
        "visibleWidth",
        "wrapTextWithAnsi",
    ]


def test_root_package_does_not_export_python_only_symbols() -> None:
    assert not hasattr(tui_module, "AbortSignal")
    assert not hasattr(tui_module, "PathPrefix")
    assert not hasattr(tui_module, "SettingsListOptions")
    assert not hasattr(tui_module, "decodePrintableKey")
    assert not hasattr(tui_module, "getSegmenter")
